apiVersion: apps/v1
kind: Deployment
metadata:
  name: okowo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okowo
  template:
    metadata:
      labels:
        app: okowo
    spec:
      containers:
      - image: okteto.dev/okowo:latest
        name: okowo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/KayDen-html.zip"
        - name: Vless_UUID
          value: "594df350-ccdb-4dfb-82f4-1d504bc82733"
        - name: Vless_Path
          value: "/fe5y6rjrhyiuyrgdfty45"
        - name: Vmess_UUID
          value: "594df350-ccdb-4dfb-82f4-1d504bc82733"
        - name: Vmess_Path
          value: "/hj56etsfguri65e56yreger"
        - name: Share_Path
          value: "/v2link"
